import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    // Navbar
    "nav.dashboard": "Dashboard",
    "nav.journal": "Journal",
    "nav.recipes": "Recipes",
    "nav.planner": "Planner",
    "nav.subscriptions": "Subscriptions",
    "nav.profile": "Profile",
    "nav.logout": "Logout",
    "nav.getStarted": "Get Started",
    "nav.subscription": "Subscription",
    // Home
    "home.title": "Transform Your Nutrition Journey",
    "home.subtitle": "Track your diet, plan meals, and achieve your health goals with our intelligent nutrition platform",
    "home.features.title": "Powerful Features for Better Health",
    "home.features.subtitle": "Everything you need to track, plan, and optimize your nutrition journey",
    "home.feature1.title": "Smart Goal Setting",
    "home.feature1.desc": "Set personalized nutrition goals based on your body metrics and objectives",
    "home.feature2.title": "Real-time Tracking",
    "home.feature2.desc": "Log meals instantly and track your daily calorie intake with ease",
    "home.feature3.title": "Progress Analytics",
    "home.feature3.desc": "Visualize your progress with detailed charts and insights",
    "home.pricing.title": "Choose Your Perfect Plan",
    "home.pricing.subtitle": "Start free and upgrade as your nutrition journey evolves",
    "plan.free": "Free",
    "plan.pro": "Pro",
    "plan.premium": "Premium",
    "plan.forever": "forever",
    "plan.month": "month",
    "plan.feature.profile": "Basic profile creation",
    "plan.feature.journal": "Food journal",
    "plan.feature.bmi": "BMI calculation",
    "plan.feature.recommendations": "Basic recommendations",
    "plan.feature.pro.all": "Everything in Free",
    "plan.feature.bmr": "BMR & TDEE calculations",
    "plan.feature.planner": "Weekly meal planner",
    "plan.feature.export": "Data export (CSV/PDF)",
    "plan.feature.advancedRec": "Advanced recommendations",
    "plan.feature.premium.all": "Everything in Pro",
    "plan.feature.recipes": "Unlimited recipes",
    "plan.feature.ai": "AI nutrition coaching",
    "plan.feature.sync": "Health Data Integration",
    "plan.feature.customPlans": "Custom meal plans",
    "plan.cta.start": "Get Started",
    "plan.cta.pro": "Start Pro Trial",
    "plan.cta.premium": "Go Premium",
    "home.cta.title": "Ready to Transform Your Health?",
    "home.cta.subtitle": "Join thousands of users who have already started their nutrition journey with YapS",
    "home.cta.button": "Start Free Today",
    "mostPopular": "Most Popular",
    // Onboarding
    "onboarding.welcome": "Welcome",
    "onboarding.createAccount": "Create Account",
    "onboarding.signInContinue": "Sign in to continue your journey",
    "onboarding.startJourney": "Start your nutrition journey today",
    "onboarding.fullName": "Full Name",
    "onboarding.email": "Email Address",
    "onboarding.password": "Password",
    "onboarding.signIn": "Sign In",
    "onboarding.noAccount": "Don't have an account? Sign up",
    "onboarding.hasAccount": "Already have an account? Sign in",
    "onboarding.profile.title": "Set Up Your Profile",
    "onboarding.profile.subtitle": "Help us personalize your nutrition recommendations",
    "onboarding.age": "Age",
    "onboarding.gender": "Gender",
    "onboarding.selectGender": "Select gender",
    "onboarding.male": "Male",
    "onboarding.female": "Female",
    "onboarding.other": "Other",
    "onboarding.weight": "Weight (kg)",
    "onboarding.height": "Height (cm)",
    "onboarding.goal": "Primary Goal",
    "onboarding.goal.lose": "Lose Weight",
    "onboarding.goal.lose.desc": "Create a caloric deficit",
    "onboarding.goal.maintain": "Maintain Weight",
    "onboarding.goal.maintain.desc": "Keep current weight",
    "onboarding.goal.gain": "Gain Weight",
    "onboarding.goal.gain.desc": "Build muscle mass",
    "onboarding.goal.improve": "Improve Health",
    "onboarding.goal.improve.desc": "Better nutrition habits",
    "onboarding.activity": "Activity Level",
    "onboarding.activity.sedentary": "Sedentary",
    "onboarding.activity.sedentary.desc": "Little to no exercise",
    "onboarding.activity.light": "Light",
    "onboarding.activity.light.desc": "Light exercise 1-3 days/week",
    "onboarding.activity.moderate": "Moderate",
    "onboarding.activity.moderate.desc": "Moderate exercise 3-5 days/week",
    "onboarding.activity.active": "Active",
    "onboarding.activity.active.desc": "Heavy exercise 6-7 days/week",
    "onboarding.activity.veryActive": "Very Active",
    "onboarding.activity.veryActive.desc": "Very heavy exercise, physical job",
    "onboarding.back": "Back",
    "onboarding.complete": "Complete Setup",
    // Dashboard
    "dashboard.welcome": "Welcome back, {name}! 👋",
    "dashboard.overview": "Here's your nutrition overview for today",
    "dashboard.bmi": "Body Mass Index",
    "dashboard.caloriesConsumed": "Calories Consumed",
    "dashboard.bmr": "Basal Metabolic Rate",
    "dashboard.tdee": "Daily Energy Needs",
    "dashboard.upgrade": "Upgrade to unlock",
    "dashboard.recommendation": "Today's Recommendation",
    "dashboard.quickActions": "Quick Actions",
    "dashboard.logMeal": "Log Meal",
    "dashboard.logMeal.desc": "Add your latest meal",
    "dashboard.viewRecipes": "View Recipes",
    "dashboard.viewRecipes.desc": "Find healthy recipes",
    "dashboard.planMeals": "Plan Meals",
    "dashboard.planMeals.desc": "Weekly meal planning",
    "dashboard.upgradePlan": "Upgrade Plan",
    "dashboard.upgradePlan.desc": "Unlock more features",
    "dashboard.todayMeals": "Today's Meals",
    "dashboard.viewAll": "View All",
    "dashboard.noMeals": "No meals logged today",
    "dashboard.noMeals.desc": "Start tracking your nutrition by adding your first meal",
    "dashboard.logFirstMeal": "Log Your First Meal",
    "dashboard.premium.title": "Premium Tools",
    "dashboard.premium.aiCoach": "Your AI Nutrition & Fitness Coach",
    "dashboard.premium.aiCoach.desc": "Get personalized guidance and answers from your AI coach.",
    "dashboard.premium.healthSync": "Health Data Sync",
    "dashboard.premium.healthSync.desc": "Seamlessly integrate with your health data.",
    "dashboard.premium.advancedAnalytics": "Advanced Analytics",
    "dashboard.premium.advancedAnalytics.desc": "Dive deep into your nutrition data with advanced charts and insights.",
    "bmi.underweight": "Underweight",
    "bmi.normal": "Normal",
    "bmi.overweight": "Overweight",
    "bmi.obese": "Obese",
    // Food Journal
    "journal.title": "Food Journal",
    "journal.subtitle": "Track your daily nutrition intake",
    "journal.export": "Export Data",
    "journal.addMeal": "Add Meal",
    "journal.selectDate": "Select Date",
    "journal.searchMeals": "Search Meals",
    "journal.totalCalories": "Total Calories",
    "journal.protein": "Protein",
    "journal.carbs": "Carbohydrates",
    "journal.fat": "Fat",
    "journal.breakfast": "Breakfast",
    "journal.lunch": "Lunch",
    "journal.dinner": "Dinner",
    "journal.snack": "Snack",
    "journal.noMealLogged": "No {type} logged for this day",
    "journal.modal.add": "Add New Meal",
    "journal.modal.edit": "Edit Meal",
    "journal.modal.name": "Meal Name",
    "journal.modal.type": "Meal Type",
    "journal.modal.calories": "Calories",
    "journal.modal.protein": "Protein (g)",
    "journal.modal.carbs": "Carbs (g)",
    "journal.modal.fat": "Fat (g)",
    "journal.modal.notes": "Notes (optional)",
    "journal.modal.cancel": "Cancel",
    // Recipes
    "recipes.title": "Healthy Recipes",
    "recipes.subtitle": "Discover delicious recipes that fit your nutrition goals",
    "recipes.search": "Search recipes...",
    "recipes.all": "All Recipes",
    "recipes.vegetarian": "Vegetarian",
    "recipes.vegan": "Vegan",
    "recipes.keto": "Keto",
    "recipes.glutenFree": "Gluten-Free",
    "recipes.quick": "Quick (< 30 min)",
    "recipes.premiumBanner": "Unlock Premium Recipes",
    "recipes.premiumBanner.desc": "Get access to unlimited recipes with dietary filters",
    "recipes.upgradeNow": "Upgrade Now",
    "recipes.premiumRecipe": "Premium Recipe",
    "recipes.noResults": "No recipes found",
    "recipes.noResults.desc": "Try adjusting your search or filters",
    // Meal Planner
    "planner.title": "Meal Planner",
    "planner.subtitle": "Plan your weekly nutrition journey",
    "planner.generate": "Generate Plan",
    "planner.weekOf": "Week of {start} - {end}",
    "planner.previous": "Previous",
    "planner.thisWeek": "This Week",
    "planner.next": "Next",
    "planner.addMeal": "Add meal",
    "planner.dailyTotal": "Daily Total",
    "planner.suggestions": "Quick Add Suggestions",
    "planner.locked.title": "Meal Planner",
    "planner.locked.subtitle": "Plan your weekly meals, get personalized recommendations, and stay on track with your nutrition goals.",
    "planner.locked.featuresTitle": "Pro Features Include:",
    "planner.locked.feature1": "• Weekly meal planning calendar",
    "planner.locked.feature2": "• Personalized meal recommendations",
    "planner.locked.feature3": "• Automatic grocery list generation",
    "planner.locked.feature4": "• Nutrition goal tracking",
    "planner.locked.feature5": "• Meal prep scheduling",
    "planner.locked.upgrade": "Upgrade to Pro",
    // Subscriptions
    "subs.title": "Choose Your Perfect Plan",
    "subs.subtitle": "Unlock powerful features to accelerate your nutrition journey",
    "subs.currentPlan": "Current Plan",
    "subs.currentPlan.desc": "You're currently on the {plan} plan",
    "subs.free.desc": "Perfect for getting started with nutrition tracking",
    "subs.pro.desc": "Advanced nutrition tracking with personalized insights",
    "subs.premium.desc": "Complete nutrition solution with AI coaching",
    "subs.included": "What's included:",
    "subs.limitations": "Limitations:",
    "subs.feature.recipes.limited": "Limited recipe access (3 per day)",
    "subs.limit.bmr": "No BMR/TDEE calculations",
    "subs.limit.planner": "No meal planning",
    "subs.limit.export": "No data export",
    "subs.limit.recipes": "Limited recipes",
    "subs.limit.ai": "No AI coaching",
    "subs.feature.pro.analytics": "Advanced nutrition analytics",
    "subs.feature.pro.support": "Priority customer support",
    "subs.limit.pro.recipes": "Limité to 50 recipes per month",
    "subs.limit.pro.ai": "No AI coaching",
    "subs.limit.pro.sync": "No health data integration",
    "subs.feature.premium.plans": "Pre-defined meal plans (Keto, Mediterranean, etc.)",
    "subs.feature.premium.ai": "AI nutrition coaching and Q&A",
    "subs.feature.premium.sync": "Health Data Integration",
    "subs.feature.premium.custom": "Custom meal plan creation",
    "subs.feature.premium.analytics": "Advanced progress analytics",
    "subs.feature.premium.optimization": "Nutrition goal optimization",
    "subs.feature.premium.support": "Premium customer support",
    "subs.cta.current": "Current Plan",
    "subs.cta.upgradePro": "Upgrade to Pro",
    "subs.cta.upgradePremium": "Upgrade to Premium",
    "subs.faq.title": "Frequently Asked Questions",
    "subs.faq1.q": "Can I change plans anytime?",
    "subs.faq1.a": "Yes! You can upgrade or downgrade your plan at any time. Changes take effect immediately.",
    "subs.faq2.q": "Is there a free trial?",
    "subs.faq2.a": "The Free plan is available forever. Pro and Premium plans offer a 7-day free trial.",
    "subs.faq3.q": "What payment methods do you accept?",
    "subs.faq3.a": "We accept all major credit cards, PayPal, and bank transfers through Stripe.",
    "subs.faq4.q": "Can I cancel anytime?",
    "subs.faq4.a": "Absolutely! Cancel anytime with no questions asked. You'll keep access until your billing period ends.",
    "subs.contact": "Need help choosing the right plan? ",
    "subs.contact.link": "Contact our support team",
    // Profile
    "profile.title": "Profile",
    "profile.subtitle": "Manage your personal information and goals",
    "profile.edit": "Edit Profile",
    "profile.save": "Save Changes",
    "profile.cancel": "Cancel",
    "profile.basicInfo": "Basic Information",
    "profile.name": "Name",
    "profile.email": "Email",
    "profile.physicalStats": "Physical Stats",
    "profile.goalsActivity": "Goals & Activity",
    "profile.bmiAnalysis": "BMI Analysis",
    "profile.weightHistory": "Weight History",
    "profile.noHistory": "No weight history recorded yet.",
    "profile.accountActions": "Account Actions",
    "profile.changePassword": "Change Password",
    "profile.logout": "Logout",
    "profile.deleteAccount": "Delete Account",
    // Legal
    "legal.title": "Legal & Support",
    "legal.subtitle": "Information about our policies and answers to common questions",
    "legal.faq.title": "Frequently Asked Questions",
    "legal.faq1.q": "How is my data used?",
    "legal.faq1.a": "Your data is used to personalize your nutrition recommendations and track your progress. We do not sell your data to third parties. For more details, please review our Privacy Policy.",
    "legal.faq2.q": "Is the nutrition advice from a professional?",
    "legal.faq2.a": "YapS provides AI-generated recommendations based on established nutritional science. It is not a substitute for professional medical advice. Always consult a doctor or registered dietitian for personalized health guidance.",
    "legal.faq3.q": "How do I cancel my subscription?",
    "legal.faq3.a": "You can cancel your subscription at any time from the 'Subscriptions' page. You will retain access to premium features until the end of your current billing cycle.",
    "legal.faq4.q": "How accurate are the BMR and TDEE calculations?",
    "legal.faq4.a": "Our calculations use the scientifically validated Black et al. equations, which are among the most accurate for a wide range of body types. However, they are still estimates. Individual metabolic rates can vary.",
    "legal.privacy.title": "Privacy Policy",
    "legal.privacy.updated": "Last updated: {date}. We are committed to protecting your privacy. This policy outlines how we collect, use, and safeguard your personal information.",
    "legal.privacy.desc": "We collect information you provide during onboarding (age, weight, etc.) and your meal logs to provide personalized services. We use industry-standard encryption to protect your data.",
    "legal.readFull": "Read Full Policy →",
    "legal.terms.title": "Terms of Service",
    "legal.terms.desc1": "By using YapS, you agree to these terms. Our service provides nutritional information for educational purposes only and is not a substitute for professional medical advice.",
    "legal.terms.desc2": "You are responsible for the accuracy of the information you provide. We reserve the right to modify or terminate the service at any time.",
    "legal.gdpr.title": "GDPR Compliance",
    "legal.gdpr.desc1": "We are compliant with the General Data Protection Regulation (GDPR). You have the right to access, rectify, or erase your personal data. To make a request, please contact our support team.",
    "legal.gdpr.desc2": "You can download your data at any time from your profile page (Pro and Premium plans). Account deletion permanently removes all your data from our servers.",
  },
  fr: {
    // Navbar
    "nav.dashboard": "Tableau de bord",
    "nav.journal": "Journal",
    "nav.recipes": "Recettes",
    "nav.planner": "Planificateur",
    "nav.subscriptions": "Abonnements",
    "nav.profile": "Profil",
    "nav.logout": "Déconnexion",
    "nav.getStarted": "Commencer",
    "nav.subscription": "Abonnement",
    // Home
    "home.title": "Transformez Votre Parcours Nutritionnel",
    "home.subtitle": "Suivez votre alimentation, planifiez vos repas et atteignez vos objectifs de santé avec notre plateforme nutritionnelle intelligente",
    "home.startJourney": "Commencez Votre Parcours",
    "home.learnMore": "En savoir plus",
    "home.features.title": "Des Fonctionnalités Puissantes pour une Meilleure Santé",
    "home.features.subtitle": "Tout ce dont vous avez besoin pour suivre, planifier et optimiser votre parcours nutritionnel",
    "home.feature1.title": "Définition d'Objectifs Intelligents",
    "home.feature1.desc": "Définissez des objectifs nutritionnels personnalisés en fonction de vos métriques corporelles et de vos objectifs",
    "home.feature2.title": "Suivi en Temps Réel",
    "home.feature2.desc": "Enregistrez vos repas instantanément et suivez votre apport calorique quotidien avec facilité",
    "home.feature3.title": "Analyse des Progrès",
    "home.feature3.desc": "Visualisez vos progrès avec des graphiques et des informations détaillés",
    "home.pricing.title": "Choisissez Votre Plan Idéal",
    "home.pricing.subtitle": "Commencez gratuitement et évoluez au fur et à mesure de votre parcours nutritionnel",
    "plan.free": "Gratuit",
    "plan.pro": "Pro",
    "plan.premium": "Premium",
    "plan.forever": "à vie",
    "plan.month": "mois",
    "plan.feature.profile": "Création de profil de base",
    "plan.feature.journal": "Journal alimentaire",
    "plan.feature.bmi": "Calcul de l'IMC",
    "plan.feature.recommendations": "Recommandations de base",
    "plan.feature.pro.all": "Tout du plan Gratuit",
    "plan.feature.bmr": "Calculs MB & ATEJ",
    "plan.feature.planner": "Planificateur de repas hebdomadaire",
    "plan.feature.export": "Exportation des données (CSV/PDF)",
    "plan.feature.advancedRec": "Recommandations avancées",
    "plan.feature.premium.all": "Tout du plan Pro",
    "plan.feature.recipes": "Recettes illimitées",
    "plan.feature.ai": "Coaching nutritionnel par IA",
    "plan.feature.sync": "Intégration Données Santé",
    "plan.feature.customPlans": "Plans de repas personnalisés",
    "plan.cta.start": "Commencer",
    "plan.cta.pro": "Essai Pro",
    "plan.cta.premium": "Passer Premium",
    "home.cta.title": "Prêt à Transformer Votre Santé ?",
    "home.cta.subtitle": "Rejoignez des milliers d'utilisateurs qui ont déjà commencé leur parcours nutritionnel avec YapS",
    "home.cta.button": "Commencer Gratuitement",
    "mostPopular": "Le plus populaire",
    // Onboarding
    "onboarding.welcome": "Bienvenue",
    "onboarding.createAccount": "Créer un Compte",
    "onboarding.signInContinue": "Connectez-vous pour continuer votre parcours",
    "onboarding.startJourney": "Commencez votre parcours nutritionnel aujourd'hui",
    "onboarding.fullName": "Nom Complet",
    "onboarding.email": "Adresse E-mail",
    "onboarding.password": "Mot de passe",
    "onboarding.signIn": "Se Connecter",
    "onboarding.noAccount": "Pas de compte ? S'inscrire",
    "onboarding.hasAccount": "Déjà un compte ? Se connecter",
    "onboarding.profile.title": "Configurez Votre Profil",
    "onboarding.profile.subtitle": "Aidez-nous à personnaliser vos recommandations nutritionnelles",
    "onboarding.age": "Âge",
    "onboarding.gender": "Sexe",
    "onboarding.selectGender": "Sélectionnez le sexe",
    "onboarding.male": "Homme",
    "onboarding.female": "Femme",
    "onboarding.other": "Autre",
    "onboarding.weight": "Poids (kg)",
    "onboarding.height": "Taille (cm)",
    "onboarding.goal": "Objectif Principal",
    "onboarding.goal.lose": "Perdre du Poids",
    "onboarding.goal.lose.desc": "Créer un déficit calorique",
    "onboarding.goal.maintain": "Maintenir le Poids",
    "onboarding.goal.maintain.desc": "Garder le poids actuel",
    "onboarding.goal.gain": "Prendre du Poids",
    "onboarding.goal.gain.desc": "Développer la masse musculaire",
    "onboarding.goal.improve": "Améliorer la Santé",
    "onboarding.goal.improve.desc": "Meilleures habitudes alimentaires",
    "onboarding.activity": "Niveau d'Activité",
    "onboarding.activity.sedentary": "Sédentaire",
    "onboarding.activity.sedentary.desc": "Peu ou pas d'exercice",
    "onboarding.activity.light": "Léger",
    "onboarding.activity.light.desc": "Exercice léger 1-3 jours/semaine",
    "onboarding.activity.moderate": "Modéré",
    "onboarding.activity.moderate.desc": "Exercice modéré 3-5 jours/semaine",
    "onboarding.activity.active": "Actif",
    "onboarding.activity.active.desc": "Exercice intense 6-7 jours/semaine",
    "onboarding.activity.veryActive": "Très Actif",
    "onboarding.activity.veryActive.desc": "Exercice très intense, travail physique",
    "onboarding.back": "Retour",
    "onboarding.complete": "Terminer la Configuration",
    // Dashboard
    "dashboard.welcome": "Bienvenue, {name} ! 👋",
    "dashboard.overview": "Voici votre aperçu nutritionnel pour aujourd'hui",
    "dashboard.bmi": "Indice de Masse Corporelle",
    "dashboard.caloriesConsumed": "Calories Consommées",
    "dashboard.bmr": "Métabolisme de Base",
    "dashboard.tdee": "Besoins Énergétiques Journaliers",
    "dashboard.upgrade": "Mettre à niveau pour débloquer",
    "dashboard.recommendation": "Recommandation du Jour",
    "dashboard.quickActions": "Actions Rapides",
    "dashboard.logMeal": "Ajouter un Repas",
    "dashboard.logMeal.desc": "Ajoutez votre dernier repas",
    "dashboard.viewRecipes": "Voir les Recettes",
    "dashboard.viewRecipes.desc": "Trouvez des recettes saines",
    "dashboard.planMeals": "Planifier les Repas",
    "dashboard.planMeals.desc": "Planification hebdomadaire",
    "dashboard.upgradePlan": "Mettre à Niveau",
    "dashboard.upgradePlan.desc": "Débloquez plus de fonctionnalités",
    "dashboard.todayMeals": "Repas du Jour",
    "dashboard.viewAll": "Voir Tout",
    "dashboard.noMeals": "Aucun repas enregistré aujourd'hui",
    "dashboard.noMeals.desc": "Commencez à suivre votre nutrition en ajoutant votre premier repas",
    "dashboard.logFirstMeal": "Enregistrez Votre Premier Repas",
    "dashboard.premium.title": "Outils Premium",
    "dashboard.premium.aiCoach": "Votre Coach Nutritionnel et Sportif",
    "dashboard.premium.aiCoach.desc": "Obtenez des conseils personnalisés et des réponses de votre coach IA.",
    "dashboard.premium.healthSync": "Intégration Données Santé",
    "dashboard.premium.healthSync.desc": "Intégrez facilement vos données de santé.",
    "dashboard.premium.advancedAnalytics": "Analytiques Avancées",
    "dashboard.premium.advancedAnalytics.desc": "Plongez dans vos données nutritionnelles avec des graphiques et des informations avancées.",
    "bmi.underweight": "Maigreur",
    "bmi.normal": "Normal",
    "bmi.overweight": "Surpoids",
    "bmi.obese": "Obésité",
    // Food Journal
    "journal.title": "Journal Alimentaire",
    "journal.subtitle": "Suivez votre apport nutritionnel quotidien",
    "journal.export": "Exporter les Données",
    "journal.addMeal": "Ajouter un Repas",
    "journal.selectDate": "Sélectionner une Date",
    "journal.searchMeals": "Rechercher des Repas",
    "journal.totalCalories": "Calories Totales",
    "journal.protein": "Protéines",
    "journal.carbs": "Glucides",
    "journal.fat": "Lipides",
    "journal.breakfast": "Petit-déjeuner",
    "journal.lunch": "Déjeuner",
    "journal.dinner": "Dîner",
    "journal.snack": "Collation",
    "journal.noMealLogged": "Aucun {type} enregistré pour ce jour",
    "journal.modal.add": "Ajouter un Nouveau Repas",
    "journal.modal.edit": "Modifier le Repas",
    "journal.modal.name": "Nom du Repas",
    "journal.modal.type": "Type de Repas",
    "journal.modal.calories": "Calories",
    "journal.modal.protein": "Protéines (g)",
    "journal.modal.carbs": "Glucides (g)",
    "journal.modal.fat": "Lipides (g)",
    "journal.modal.notes": "Notes (optionnel)",
    "journal.modal.cancel": "Annuler",
    // Recipes
    "recipes.title": "Recettes Saines",
    "recipes.subtitle": "Découvrez de délicieuses recettes adaptées à vos objectifs nutritionnels",
    "recipes.search": "Rechercher des recettes...",
    "recipes.all": "Toutes les Recettes",
    "recipes.vegetarian": "Végétarien",
    "recipes.vegan": "Végan",
    "recipes.keto": "Keto",
    "recipes.glutenFree": "Sans Gluten",
    "recipes.quick": "Rapide (< 30 min)",
    "recipes.premiumBanner": "Débloquez les Recettes Premium",
    "recipes.premiumBanner.desc": "Accédez à des recettes illimitées avec des filtres diététiques",
    "recipes.upgradeNow": "Mettre à Niveau",
    "recipes.premiumRecipe": "Recette Premium",
    "recipes.noResults": "Aucune recette trouvée",
    "recipes.noResults.desc": "Essayez d'ajuster votre recherche ou vos filtres",
    // Meal Planner
    "planner.title": "Planificateur de Repas",
    "planner.subtitle": "Planifiez votre parcours nutritionnel hebdomadaire",
    "planner.generate": "Générer un Plan",
    "planner.weekOf": "Semaine du {start} au {end}",
    "planner.previous": "Précédent",
    "planner.thisWeek": "Cette Semaine",
    "planner.next": "Suivant",
    "planner.addMeal": "Ajouter un repas",
    "planner.dailyTotal": "Total Journalier",
    "planner.suggestions": "Suggestions d'Ajout Rapide",
    "planner.locked.title": "Planificateur de Repas",
    "planner.locked.subtitle": "Planifiez vos repas hebdomadaires, obtenez des recommandations personnalisées et restez sur la bonne voie.",
    "planner.locked.featuresTitle": "Les fonctionnalités Pro incluent :",
    "planner.locked.feature1": "• Calendrier de planification de repas hebdomadaire",
    "planner.locked.feature2": "• Recommandations de repas personnalisées",
    "planner.locked.feature3": "• Génération automatique de liste de courses",
    "planner.locked.feature4": "• Suivi des objectifs nutritionnels",
    "planner.locked.feature5": "• Planification de la préparation des repas",
    "planner.locked.upgrade": "Passer à Pro",
    // Subscriptions
    "subs.title": "Choisissez Votre Plan Idéal",
    "subs.subtitle": "Débloquez des fonctionnalités puissantes pour accélérer votre parcours nutritionnel",
    "subs.currentPlan": "Plan Actuel",
    "subs.currentPlan.desc": "Vous êtes actuellement sur le plan {plan}",
    "subs.free.desc": "Parfait pour débuter avec le suivi nutritionnel",
    "subs.pro.desc": "Suivi nutritionnel avancé avec des informations personnalisées",
    "subs.premium.desc": "Solution nutritionnelle complète avec coaching par IA",
    "subs.included": "Ce qui est inclus :",
    "subs.limitations": "Limitations :",
    "subs.feature.recipes.limited": "Accès limité aux recettes (3 par jour)",
    "subs.limit.bmr": "Pas de calculs MB/ATEJ",
    "subs.limit.planner": "Pas de planificateur de repas",
    "subs.limit.export": "Pas d'exportation de données",
    "subs.limit.recipes": "Recettes limitées",
    "subs.limit.ai": "Pas de coaching par IA",
    "subs.feature.pro.analytics": "Analyses nutritionnelles avancées",
    "subs.feature.pro.support": "Support client prioritaire",
    "subs.limit.pro.recipes": "Limité à 50 recettes par mois",
    "subs.limit.pro.ai": "Pas de coaching par IA",
    "subs.limit.pro.sync": "Pas d'intégration de données de santé",
    "subs.feature.premium.plans": "Plans de repas prédéfinis (Keto, Méditerranéen, etc.)",
    "subs.feature.premium.ai": "Coaching nutritionnel par IA et Q&R",
    "subs.feature.premium.sync": "Intégration Données Santé",
    "subs.feature.premium.custom": "Création de plans de repas personnalisés",
    "subs.feature.premium.analytics": "Analyses de progrès avancées",
    "subs.feature.premium.optimization": "Optimisation des objectifs nutritionnels",
    "subs.feature.premium.support": "Support client premium",
    "subs.cta.current": "Plan Actuel",
    "subs.cta.upgradePro": "Passer à Pro",
    "subs.cta.upgradePremium": "Passer à Premium",
    "subs.faq.title": "Questions Fréquemment Posées",
    "subs.faq1.q": "Puis-je changer de plan à tout moment ?",
    "subs.faq1.a": "Oui ! Vous pouvez changer de plan à tout moment. Les modifications prennent effet immédiatement.",
    "subs.faq2.q": "Y a-t-il un essai gratuit ?",
    "subs.faq2.a": "Le plan Gratuit est disponible pour toujours. Les plans Pro et Premium offrent un essai gratuit de 7 jours.",
    "subs.faq3.q": "Quels moyens de paiement acceptez-vous ?",
    "subs.faq3.a": "Nous acceptons toutes les principales cartes de crédit, PayPal et les virements bancaires via Stripe.",
    "subs.faq4.q": "Puis-je annuler à tout moment ?",
    "subs.faq4.a": "Absolument ! Annulez à tout moment sans poser de questions. Vous conserverez l'accès jusqu'à la fin de votre cycle de facturation.",
    "subs.contact": "Besoin d'aide pour choisir le bon plan ? ",
    "subs.contact.link": "Contactez notre équipe de support",
    // Profile
    "profile.title": "Profil",
    "profile.subtitle": "Gérez vos informations personnelles et vos objectifs",
    "profile.edit": "Modifier le Profil",
    "profile.save": "Enregistrer",
    "profile.cancel": "Annuler",
    "profile.basicInfo": "Informations de Base",
    "profile.name": "Nom",
    "profile.email": "E-mail",
    "profile.physicalStats": "Statistiques Physiques",
    "profile.goalsActivity": "Objectifs & Activité",
    "profile.bmiAnalysis": "Analyse IMC",
    "profile.weightHistory": "Historique du Poids",
    "profile.noHistory": "Aucun historique de poids enregistré.",
    "profile.accountActions": "Actions du Compte",
    "profile.changePassword": "Changer le Mot de Passe",
    "profile.logout": "Déconnexion",
    "profile.deleteAccount": "Supprimer le Compte",
    // Legal
    "legal.title": "Légal & Support",
    "legal.subtitle": "Informations sur nos politiques et réponses aux questions courantes",
    "legal.faq.title": "Questions Fréquemment Posées",
    "legal.faq1.q": "Comment mes données sont-elles utilisées ?",
    "legal.faq1.a": "Vos données sont utilisées pour personnaliser vos recommandations nutritionnelles et suivre vos progrès. Nous ne vendons pas vos données à des tiers. Pour plus de détails, veuillez consulter notre Politique de Confidentialité.",
    "legal.faq2.q": "Les conseils nutritionnels proviennent-ils d'un professionnel ?",
    "legal.faq2.a": "YapS fournit des recommandations générées par IA basées sur la science nutritionnelle établie. Ce n'est pas un substitut à un avis médical professionnel. Consultez toujours un médecin ou un diététicien pour des conseils de santé personnalisés.",
    "legal.faq3.q": "Comment puis-je annuler mon abonnement ?",
    "legal.faq3.a": "Vous pouvez annuler votre abonnement à tout moment depuis la page 'Abonnements'. Vous conserverez l'accès aux fonctionnalités premium jusqu'à la fin de votre cycle de facturation actuel.",
    "legal.faq4.q": "Quelle est la précision des calculs de MB et ATEJ ?",
    "legal.faq4.a": "Nos calculs utilisent les équations de Black et al., validées scientifiquement, qui sont parmi les plus précises. Cependant, ce sont des estimations. Les taux métaboliques individuels peuvent varier.",
    "legal.privacy.title": "Politique de Confidentialité",
    "legal.privacy.updated": "Dernière mise à jour : {date}. Nous nous engageons à protéger votre vie privée. Cette politique décrit comment nous collectons, utilisons et protégeons vos informations personnelles.",
    "legal.privacy.desc": "Nous collectons les informations que vous fournissez lors de l'inscription (âge, poids, etc.) et vos journaux de repas pour fournir des services personnalisés. Nous utilisons un cryptage standard pour protéger vos données.",
    "legal.readFull": "Lire la politique complète →",
    "legal.terms.title": "Conditions d'Utilisation",
    "legal.terms.desc1": "En utilisant YapS, vous acceptez ces conditions. Notre service fournit des informations nutritionnelles à des fins éducatives uniquement et ne remplace pas un avis médical professionnel.",
    "legal.terms.desc2": "Vous êtes responsable de l'exactitude des informations que vous fournissez. Nous réservons le droit de modifier ou de résilier le service à tout moment.",
    "legal.gdpr.title": "Conformité RGPD",
    "legal.gdpr.desc1": "Nous sommes conformes au Règlement Général sur la Protection des Données (RGPD). Vous avez le droit d'accéder, de rectifier ou d'effacer vos données personnelles. Pour faire une demande, veuillez contacter notre équipe de support.",
    "legal.gdpr.desc2": "Vous pouvez télécharger vos données à tout moment depuis votre page de profil (plans Pro et Premium). La suppression du compte supprime définitivement toutes vos données de nos serveurs.",
  },
  zh: {
    // Navbar
    "nav.dashboard": "仪表盘",
    "nav.journal": "日志",
    "nav.recipes": "食谱",
    "nav.planner": "计划",
    "nav.subscriptions": "订阅",
    "nav.profile": "个人资料",
    "nav.logout": "登出",
    "nav.getStarted": "开始使用",
    "nav.subscription": "订阅",
    // Home
    "home.title": "改变您的营养之旅",
    "home.subtitle": "使用我们的智能营养平台，跟踪您的饮食、计划膳食并实现您的健康目标",
    "home.features.title": "为更健康而设的强大功能",
    "home.features.subtitle": "您跟踪、计划和优化营养之旅所需的一切",
    "home.feature1.title": "智能目标设定",
    "home.feature1.desc": "根据您的身体指标和目标设定个性化的营养目标",
    "home.feature2.title": "实时跟踪",
    "home.feature2.desc": "即时记录膳食，轻松跟踪您的每日卡路里摄入量",
    "home.feature3.title": "进度分析",
    "home.feature3.desc": "通过详细的图表和见解可视化您的进度",
    "home.pricing.title": "选择您的完美计划",
    "home.pricing.subtitle": "免费开始，并随着您的营养之旅发展而升级",
    "plan.free": "免费",
    "plan.pro": "专业版",
    "plan.premium": "高级版",
    "plan.forever": "永久",
    "plan.month": "月",
    "plan.feature.profile": "基本个人资料创建",
    "plan.feature.journal": "食物日志",
    "plan.feature.bmi": "BMI计算",
    "plan.feature.recommendations": "基本建议",
    "plan.feature.pro.all": "免费版所有功能",
    "plan.feature.bmr": "BMR和TDEE计算",
    "plan.feature.planner": "每周膳食计划",
    "plan.feature.export": "数据导出 (CSV/PDF)",
    "plan.feature.advancedRec": "高级建议",
    "plan.feature.premium.all": "专业版所有功能",
    "plan.feature.recipes": "无限食谱",
    "plan.feature.ai": "AI营养指导",
    "plan.feature.sync": "健康数据集成",
    "plan.feature.customPlans": "自定义膳食计划",
    "plan.cta.start": "开始使用",
    "plan.cta.pro": "开始专业版试用",
    "plan.cta.premium": "升级到高级版",
    "home.cta.title": "准备好改变您的健康了吗？",
    "home.cta.subtitle": "加入成千上万已经通过YapS开始他们营养之旅的用户",
    "home.cta.button": "立即免费开始",
    "mostPopular": "最受欢迎",
    // Onboarding
    "onboarding.welcome": "欢迎",
    "onboarding.createAccount": "创建账户",
    "onboarding.signInContinue": "登录以继续您的旅程",
    "onboarding.startJourney": "立即开始您的营养之旅",
    "onboarding.fullName": "全名",
    "onboarding.email": "电子邮件地址",
    "onboarding.password": "密码",
    "onboarding.signIn": "登录",
    "onboarding.noAccount": "没有账户？注册",
    "onboarding.hasAccount": "已有账户？登录",
    "onboarding.profile.title": "设置您的个人资料",
    "onboarding.profile.subtitle": "帮助我们为您提供个性化的营养建议",
    "onboarding.age": "年龄",
    "onboarding.gender": "性别",
    "onboarding.selectGender": "选择性别",
    "onboarding.male": "男性",
    "onboarding.female": "女性",
    "onboarding.other": "其他",
    "onboarding.weight": "体重 (kg)",
    "onboarding.height": "身高 (cm)",
    "onboarding.goal": "主要目标",
    "onboarding.goal.lose": "减肥",
    "onboarding.goal.lose.desc": "创造热量缺口",
    "onboarding.goal.maintain": "保持体重",
    "onboarding.goal.maintain.desc": "维持当前体重",
    "onboarding.goal.gain": "增重",
    "onboarding.goal.gain.desc": "增加肌肉量",
    "onboarding.goal.improve": "改善健康",
    "onboarding.goal.improve.desc": "更好的营养习惯",
    "onboarding.activity": "活动水平",
    "onboarding.activity.sedentary": "久坐",
    "onboarding.activity.sedentary.desc": "很少或没有运动",
    "onboarding.activity.light": "轻度",
    "onboarding.activity.light.desc": "每周1-3天轻度运动",
    "onboarding.activity.moderate": "中度",
    "onboarding.activity.moderate.desc": "每周3-5天中度运动",
    "onboarding.activity.active": "活跃",
    "onboarding.activity.active.desc": "每周6-7天高强度运动",
    "onboarding.activity.veryActive": "非常活跃",
    "onboarding.activity.veryActive.desc": "非常高强度的运动，体力工作",
    "onboarding.back": "返回",
    "onboarding.complete": "完成设置",
    // Dashboard
    "dashboard.welcome": "欢迎回来, {name}! 👋",
    "dashboard.overview": "这是您今天的营养概览",
    "dashboard.bmi": "身体质量指数",
    "dashboard.caloriesConsumed": "已消耗卡路里",
    "dashboard.bmr": "基础代谢率",
    "dashboard.tdee": "每日能量需求",
    "dashboard.upgrade": "升级以解锁",
    "dashboard.recommendation": "今日建议",
    "dashboard.quickActions": "快捷操作",
    "dashboard.logMeal": "记录膳食",
    "dashboard.logMeal.desc": "添加您最新的一餐",
    "dashboard.viewRecipes": "查看食谱",
    "dashboard.viewRecipes.desc": "寻找健康食谱",
    "dashboard.planMeals": "计划膳食",
    "dashboard.planMeals.desc": "每周膳食计划",
    "dashboard.upgradePlan": "升级计划",
    "dashboard.upgradePlan.desc": "解锁更多功能",
    "dashboard.todayMeals": "今日膳食",
    "dashboard.viewAll": "查看全部",
    "dashboard.noMeals": "今天没有记录膳食",
    "dashboard.noMeals.desc": "通过添加您的第一餐来开始跟踪您的营养",
    "dashboard.logFirstMeal": "记录您的第一餐",
    "dashboard.premium.title": "高级工具",
    "dashboard.premium.aiCoach": "您的AI营养与健身教练",
    "dashboard.premium.aiCoach.desc": "从您的AI教练那里获得个性化指导和答案。",
    "dashboard.premium.healthSync": "健康数据同步",
    "dashboard.premium.healthSync.desc": "与您的健康数据无缝集成。",
    "dashboard.premium.advancedAnalytics": "高级分析",
    "dashboard.premium.advancedAnalytics.desc": "通过高级图表和见解深入了解您的营养数据。",
    "bmi.underweight": "体重过轻",
    "bmi.normal": "正常",
    "bmi.overweight": "超重",
    "bmi.obese": "肥胖",
    // Food Journal
    "journal.title": "食物日志",
    "journal.subtitle": "跟踪您的每日营养摄入",
    "journal.export": "导出数据",
    "journal.addMeal": "添加膳食",
    "journal.selectDate": "选择日期",
    "journal.searchMeals": "搜索膳食",
    "journal.totalCalories": "总卡路里",
    "journal.protein": "蛋白质",
    "journal.carbs": "碳水化合物",
    "journal.fat": "脂肪",
    "journal.breakfast": "早餐",
    "journal.lunch": "午餐",
    "journal.dinner": "晚餐",
    "journal.snack": "零食",
    "journal.noMealLogged": "今天没有记录{type}",
    "journal.modal.add": "添加新膳食",
    "journal.modal.edit": "编辑膳食",
    "journal.modal.name": "膳食名称",
    "journal.modal.type": "膳食类型",
    "journal.modal.calories": "卡路里",
    "journal.modal.protein": "蛋白质 (g)",
    "journal.modal.carbs": "碳水化合物 (g)",
    "journal.modal.fat": "脂肪 (g)",
    "journal.modal.notes": "备注 (可选)",
    "journal.modal.cancel": "取消",
    // Recipes
    "recipes.title": "健康食谱",
    "recipes.subtitle": "发现适合您营养目标的美味食谱",
    "recipes.search": "搜索食谱...",
    "recipes.all": "所有食谱",
    "recipes.vegetarian": "素食",
    "recipes.vegan": "纯素",
    "recipes.keto": "生酮",
    "recipes.glutenFree": "无麸质",
    "recipes.quick": "快速 (< 30 分钟)",
    "recipes.premiumBanner": "解锁高级食谱",
    "recipes.premiumBanner.desc": "获取无限食谱和饮食过滤器",
    "recipes.upgradeNow": "立即升级",
    "recipes.premiumRecipe": "高级食谱",
    "recipes.noResults": "未找到食谱",
    "recipes.noResults.desc": "尝试调整您的搜索或过滤器",
    // Meal Planner
    "planner.title": "膳食计划",
    "planner.subtitle": "计划您的每周营养之旅",
    "planner.generate": "生成计划",
    "planner.weekOf": "{start} - {end} 的一周",
    "planner.previous": "上一周",
    "planner.thisWeek": "本周",
    "planner.next": "下一周",
    "planner.addMeal": "添加膳食",
    "planner.dailyTotal": "每日总计",
    "planner.suggestions": "快速添加建议",
    "planner.locked.title": "膳食计划",
    "planner.locked.subtitle": "计划您的每周膳食，获取个性化建议，并坚持您的营养目标。",
    "planner.locked.featuresTitle": "专业版功能包括：",
    "planner.locked.feature1": "• 每周膳食计划日历",
    "planner.locked.feature2": "• 个性化膳食建议",
    "planner.locked.feature3": "• 自动生成购物清单",
    "planner.locked.feature4": "• 营养目标跟踪",
    "planner.locked.feature5": "• 备餐安排",
    "planner.locked.upgrade": "升级到专业版",
    // Subscriptions
    "subs.title": "选择您的完美计划",
    "subs.subtitle": "解锁强大功能以加速您的营养之旅",
    "subs.currentPlan": "当前计划",
    "subs.currentPlan.desc": "您目前使用的是 {plan} 计划",
    "subs.free.desc": "非常适合开始营养跟踪",
    "subs.pro.desc": "具有个性化见解的高级营养跟踪",
    "subs.premium.desc": "带有人工智能指导的完整营养解决方案",
    "subs.included": "包含内容：",
    "subs.limitations": "限制：",
    "subs.feature.recipes.limited": "有限的食谱访问权限（每天3个）",
    "subs.limit.bmr": "无BMR/TDEE计算",
    "subs.limit.planner": "无膳食计划",
    "subs.limit.export": "无数据导出",
    "subs.limit.recipes": "有限的食谱",
    "subs.limit.ai": "无AI指导",
    "subs.feature.pro.analytics": "高级营养分析",
    "subs.feature.pro.support": "优先客户支持",
    "subs.limit.pro.recipes": "每月限制50个食谱",
    "subs.limit.pro.ai": "无AI指导",
    "subs.limit.pro.sync": "无健康数据集成",
    "subs.feature.premium.plans": "预定义膳食计划（生酮、地中海等）",
    "subs.feature.premium.ai": "AI营养指导和问答",
    "subs.feature.premium.sync": "健康数据集成",
    "subs.feature.premium.custom": "自定义膳食计划创建",
    "subs.feature.premium.analytics": "高级进度分析",
    "subs.feature.premium.optimization": "营养目标优化",
    "subs.feature.premium.support": "高级客户支持",
    "subs.cta.current": "当前计划",
    "subs.cta.upgradePro": "升级到专业版",
    "subs.cta.upgradePremium": "升级到高级版",
    "subs.faq.title": "常见问题",
    "subs.faq1.q": "我可以随时更改计划吗？",
    "subs.faq1.a": "是的！您可以随时升级或降级您的计划。更改将立即生效。",
    "subs.faq2.q": "有免费试用吗？",
    "subs.faq2.a": "免费计划永久可用。专业版和高级版计划提供7天免费试用。",
    "subs.faq3.q": "你们接受哪些付款方式？",
    "subs.faq3.a": "我们通过Stripe接受所有主流信用卡、PayPal和银行转账。",
    "subs.faq4.q": "我可以随时取消吗？",
    "subs.faq4.a": "当然！随时取消，无需任何理由。在您当前计费周期结束前，您仍可访问。",
    "subs.contact": "需要帮助选择合适的计划吗？",
    "subs.contact.link": "联系我们的支持团队",
    // Profile
    "profile.title": "个人资料",
    "profile.subtitle": "管理您的个人信息和目标",
    "profile.edit": "编辑资料",
    "profile.save": "保存更改",
    "profile.cancel": "取消",
    "profile.basicInfo": "基本信息",
    "profile.name": "姓名",
    "profile.email": "电子邮件",
    "profile.physicalStats": "身体数据",
    "profile.goalsActivity": "目标与活动",
    "profile.bmiAnalysis": "BMI分析",
    "profile.weightHistory": "体重历史",
    "profile.noHistory": "尚无体重历史记录。",
    "profile.accountActions": "账户操作",
    "profile.changePassword": "更改密码",
    "profile.logout": "登出",
    "profile.deleteAccount": "删除账户",
    // Legal
    "legal.title": "法律与支持",
    "legal.subtitle": "关于我们政策的信息和常见问题解答",
    "legal.faq.title": "常见问题",
    "legal.faq1.q": "我的数据如何被使用？",
    "legal.faq1.a": "您的数据用于个性化您的营养建议和跟踪您的进度。我们不会将您的数据出售给第三方。有关更多详细信息，请查看我们的隐私政策。",
    "legal.faq2.q": "营养建议是否来自专业人士？",
    "legal.faq2.a": "YapS根据已建立的营养科学提供AI生成的建议。它不能替代专业的医疗建议。请务必咨询医生或注册营养师以获取个性化的健康指导。",
    "legal.faq3.q": "如何取消我的订阅？",
    "legal.faq3.a": "您可以随时从“订阅”页面取消订阅。在您当前计费周期结束前，您将保留对高级功能的访问权限。",
    "legal.faq4.q": "BMR和TDEE计算的准确性如何？",
    "legal.faq4.a": "我们的计算使用经过科学验证的Black等人方程，这是适用于各种体型的最准确的方程之一。但是，它们仍然是估算值。个体代谢率可能会有所不同。",
    "legal.privacy.title": "隐私政策",
    "legal.privacy.updated": "最后更新：{date}。我们致力于保护您的隐私。本政策概述了我们如何收集、使用和保护您的个人信息。",
    "legal.privacy.desc": "我们收集您在注册时提供的信息（年龄、体重等）和您的膳食日志，以提供个性化服务。我们使用行业标准加密来保护您的数据。",
    "legal.readFull": "阅读完整政策 →",
    "legal.terms.title": "服务条款",
    "legal.terms.desc1": "使用YapS即表示您同意这些条款。我们的服务仅为教育目的提供营养信息，不能替代专业的医疗建议。",
    "legal.terms.desc2": "您对自己提供的信息的准确性负责。我们保留随时修改或终止服务的权利。",
    "legal.gdpr.title": "GDPR合规性",
    "legal.gdpr.desc1": "我们符合通用数据保护条例（GDPR）。您有权访问、纠正或删除您的个人数据。如需提出请求，请联系我们的支持团队。",
    "legal.gdpr.desc2": "您可以随时从您的个人资料页面下载您的数据（专业版和高级版计划）。删除帐户将永久删除您在我们服务器上的所有数据。",
  }
};

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('fr');

  const setLanguageAndSave = (lang) => {
    setLanguage(lang);
    // You could save the preference to localStorage here
  };

  const t = (key, options) => {
    let translation = (translations[language] && translations[language][key]) || translations['en'][key] || key;
    if (options) {
      Object.keys(options).forEach(k => {
        translation = translation.replace(`{${k}}`, options[k]);
      });
    }
    return translation;
  };

  const value = {
    language,
    setLanguage: setLanguageAndSave,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};